# Generated by Django 4.2.3 on 2023-07-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='contraseña',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
