# Generated by Django 4.2.3 on 2023-07-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dni', '0003_remove_userdata_contraseña_userdata_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='contraseña',
            field=models.CharField(db_column='contraseña', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
