# Generated by Django 4.2.3 on 2023-07-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dni', '0004_userdata_contraseña_alter_userdata_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='contraseña',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
